import test from 'node:test';
import assert from 'node:assert/strict';
import {emptyData,chooseWords,progressFor,parseImport,applyOps} from '../app/core.js';
import {activityKey,collectionActive,forgottenWords,inactiveQueue} from '../app/collection-learning.js';
import {lookupWords,classroomResults} from '../app/classroom.js';
import {formMatch} from '../app/morphology.js';
import {makeRound} from '../app/confusions.js';
function fixture(){const d=emptyData();d.collections={a:{id:'a',name:'Aktiv'},b:{id:'b',name:'Nachschlagen'}};d.words={x:{id:'x',collectionId:'a',latin:'amare',meanings:[['lieben']]},y:{id:'y',collectionId:'b',latin:'vox, vocis',meanings:[['Stimme']]}};d.settings[activityKey('b')]={kind:'collectionActivity',active:false};return d;}
test('Existing collections default to active; personal switch excludes all ordinary modes',()=>{const d=fixture();assert.equal(collectionActive(d,'a'),true);assert.equal(collectionActive(d,'b'),false);assert.equal(collectionActive(d,'missing'),false);for(const mode of ['smart','all','learning','refresh'])assert.ok(!chooseWords(d,['a','b'],20,mode).includes('y'));d.settings[activityKey('a')]={active:false};assert.deepEqual(chooseWords(d,['a','b']),[]);});
test('Inactive collections stay searchable and explicit check includes every word',()=>{const d=fixture();assert.equal(lookupWords(d,'Stimme')[0].id,'y');assert.deepEqual(inactiveQueue(d,['b'],'inactive-check',1),['y']);});
test('Failed checks accumulate across inactive collections; repeats do not erase failure',()=>{const d=fixture();d.collections.c={id:'c'};d.settings[activityKey('c')]={active:false};d.words.z={...d.words.y,id:'z',collectionId:'c'};d.reviews={r1:{id:'r1',wordId:'y',at:1,grade:'partial',mode:'inactive-check'},r2:{id:'r2',wordId:'z',at:2,grade:'wrong',mode:'inactive-check'},r3:{id:'r3',wordId:'y',at:3,grade:'full',repeat:true,mode:'inactive-practice'}};assert.deepEqual(forgottenWords(d).map(w=>w.id),['y','z']);assert.deepEqual(inactiveQueue(d,[],'inactive-practice',1),['y']);d.reviews.r4={id:'r4',wordId:'y',at:4,grade:'full',mode:'inactive-practice'};assert.deepEqual(forgottenWords(d).map(w=>w.id),['z']);assert.equal(progressFor('y',d.reviews).level,'known');});
test('Manual known preserves history and clears forgotten word without fake repetitions',()=>{const d=fixture();d.reviews.a={id:'a',wordId:'y',at:1,grade:'wrong',mode:'inactive-check'};d.reviews.b={id:'b',wordId:'y',at:2,grade:'full',manualKnown:true};assert.equal(progressFor('y',d.reviews).level,'known');assert.deepEqual(forgottenWords(d),[]);assert.equal(Object.keys(d.reviews).length,2);});
test('Reactivating or deleting a collection removes it from inactive practice',()=>{const d=fixture();d.reviews.a={id:'a',wordId:'y',at:1,grade:'wrong',mode:'inactive-check'};assert.equal(forgottenWords(d).length,1);d.settings[activityKey('b')].active=true;assert.equal(forgottenWords(d).length,0);delete d.collections.b;assert.equal(forgottenWords(d).length,0);});
test('Ordinary errors do not create an inactive check queue; corrected grading clears it',()=>{const d=fixture();d.reviews.a={id:'a',wordId:'y',at:1,grade:'wrong',mode:'smart'};assert.equal(forgottenWords(d).length,0);d.reviews.a.mode='inactive-check';assert.equal(forgottenWords(d).length,1);d.reviews.a.grade='full';assert.equal(forgottenWords(d).length,0);});
test('Automatic confusion rounds exclude inactive counterpart',()=>{const d=fixture();d.settings.p={kind:'confusion',id:'p',wordIds:['x','y'],createdAt:0};assert.equal(makeRound(d,['x']),null);assert.ok(makeRound(d,null,true));});
test('Explicit search forms import without altering the training prompt',()=>{const d=fixture();const result=parseImport({format:'latinio-collection',schema:1,id:'forms',name:'Formen',words:[{latin:'ferre',meanings:[['tragen']],forms:['tulisset',' tulisset ']}]},d);assert.equal(result.words[0].latin,'ferre');assert.deepEqual(result.words[0].forms,['tulisset']);assert.equal(formMatch(result.words[0],'TULISSET'),'stored');for(const forms of ['x',[3],Array(301).fill('a')])assert.throws(()=>parseImport({format:'latinio-collection',schema:1,name:'x',words:[{latin:'a',meanings:[['b']],forms}]},d));});
test('Present, perfect and noun forms are labelled suggestions, not exact analyses',()=>{for(const [latin,query] of [['amare','amat'],['amare','amavit'],['videre','vidit'],['esse','fuit'],['vox, vocis','vocibus'],['vox, vocem','voces'],['liber, libri','librorum']])assert.equal(formMatch({latin},query),'inferred',query);assert.equal(formMatch({latin:'vox, vocis'},'voxyzzz'),null);const d=fixture();assert.equal(lookupWords(d,'vocem')[0].id,'y');assert.match(classroomResults(d,'vocem',x=>x),/Mögliche gebeugte Form/);});
test('Collection activity and check metadata survive cloud-operation replay',()=>{const d=fixture();const ops=[{entity:'settings',key:activityKey('a'),value:{kind:'collectionActivity',active:false}},{entity:'reviews',key:'r',value:{id:'r',wordId:'x',grade:'wrong',at:1,mode:'inactive-check'}}];const restored=applyOps(d,ops);assert.equal(collectionActive(restored,'a'),false);assert.deepEqual(forgottenWords(restored).map(w=>w.id),['x']);assert.equal(collectionActive(d,'a'),true);});
