import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
import {emptyData,chooseWords,applyOps} from '../app/core.js';
import {sortedCollections,refreshDecks,trainingDecks,wordsForDecks,deckMembers,pendingMembers,saveDeck,checkResultWords,wordEnabled} from '../app/refresh-decks.js';
import {collectionActive,forgottenWords,inactiveQueue} from '../app/collection-learning.js';
import {refreshCreate,refreshEditor,refreshList,checkPicker} from '../app/refresh-ui.js';
import {lookupWords} from '../app/classroom.js';
import {harness} from './google-harness.mjs';
const h=x=>String(x).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('"','&quot;');
function fixture(){const d=emptyData();for(const n of [10,2,1]){d.collections['c'+n]={id:'c'+n,name:'Lektion '+n};d.words['w'+n]={id:'w'+n,collectionId:'c'+n,latin:'vox'+n,meanings:[['Stimme']]};d.settings['collection-active_c'+n]={active:false};}return d;}
function deck(d,ids=['w1','w2'],at=10){const r=saveDeck(d,null,'refresh_r','Auffrischen 1–2',ids,at);d.settings[r.id]=r;return r;}
test('Refresh workflow starts with a named empty deck and binds checks/results to that deck',()=>{
 const d=fixture();const r=deck(d,[]);assert.equal(deckMembers(d,r).length,0);assert.match(refreshCreate(),/id="refresh-create-form"/);assert.doesNotMatch(refreshCreate(),/name="word"/);
 const list=refreshList(d,h);assert.match(list,/data-action="refresh-new"/);assert.doesNotMatch(list,/Kann ich sie noch/);assert.match(list,/Vokabeln manuell hinzufügen/);
 assert.match(checkPicker(d,h,r.id),/data-target="refresh_r"/);
 const editor=refreshEditor(d,{id:r.id,selected:['w1'],merge:true},h);assert.match(editor,/data-id="refresh_r"/);assert.doesNotMatch(editor,/name="target"/);assert.match(editor,/value="w1" checked/);
});
test('Numeric ordering everywhere uses 1, 2, 10',()=>{const d=fixture();assert.deepEqual(sortedCollections(d).map(c=>c.name),['Lektion 1','Lektion 2','Lektion 10']);const html=checkPicker(d,h);assert.ok(html.indexOf('Lektion 2')<html.indexOf('Lektion 10'));});
test('Reference decks train inactive originals once and never duplicate lookup entries',()=>{const d=fixture();const r=deck(d);assert.deepEqual(chooseWords(d,[r.id],10,'all').sort(),['w1','w2']);assert.equal(lookupWords(d,'Stimme').length,3);d.settings['collection-active_c1'].active=true;assert.equal(chooseWords(d,['c1',r.id],10,'all').filter(id=>id==='w1').length,1);assert.equal(Object.keys(d.words).length,3);assert.equal(Object.keys(d.collections).length,3);});
test('Correct initial answers after addition complete a word; repeats cannot hide errors',()=>{const d=fixture(),r=deck(d);d.reviews.old={id:'old',wordId:'w1',at:5,grade:'full'};assert.equal(pendingMembers(d,r).length,2);d.reviews.bad={id:'bad',wordId:'w1',at:11,grade:'partial'};d.reviews.repeat={id:'repeat',wordId:'w1',at:12,grade:'full',repeat:true};assert.equal(pendingMembers(d,r).length,2);d.reviews.good={id:'good',wordId:'w1',at:13,grade:'full'};assert.deepEqual(pendingMembers(d,r).map(m=>m.wordId),['w2']);assert.equal(wordEnabled(d,'w1'),true);assert.deepEqual(wordsForDecks(d,[r.id]).map(w=>w.id),['w2']);});
test('Deactivation, deletion and original edits respect reference semantics',()=>{const d=fixture(),r=deck(d);r.active=false;assert.deepEqual(chooseWords(d,[r.id]),[]);assert.equal(wordEnabled(d,'w1'),false);r.active=true;d.words.w1.latin='bearbeitet';assert.equal(wordsForDecks(d,[r.id])[0].latin,'bearbeitet');delete d.words.w1;assert.equal(deckMembers(d,r).length,1);delete d.collections.c2;assert.equal(deckMembers(d,r).length,0);});
test('Editing membership deduplicates and preserves retained progress while adding new words',()=>{const d=fixture(),r=deck(d);const updated=saveDeck(d,r,r.id,'Neuer Name',['w1','w1','w10','missing'],20);assert.deepEqual(updated.members,[{wordId:'w1',addedAt:10},{wordId:'w10',addedAt:20}]);assert.throws(()=>saveDeck(d,r,r.id,'',[],20));assert.equal(d.words.w1.latin,'vox1');});
test('Multi-lesson check and reference-deck check include all members, independent of activity',()=>{const d=fixture(),r=deck(d);assert.deepEqual(inactiveQueue(d,['c1','c2'],'inactive-check',1).sort(),['w1','w2']);assert.deepEqual(inactiveQueue(d,['c1',r.id],'inactive-check',1).sort(),['w1','w2']);});
test('Result suggestions use this round only, include partials and exclude correct/repeat answers',()=>{const d=fixture();d.reviews={a:{id:'session-0',wordId:'w1',grade:'wrong'},b:{id:'session-1',wordId:'w2',grade:'partial'},c:{id:'session-2',wordId:'w10',grade:'full'},e:{id:'session-3',wordId:'w10',grade:'wrong',repeat:true},f:{id:'other-0',wordId:'w10',grade:'wrong'}};assert.deepEqual(checkResultWords(d,{id:'session'}),['w1','w2']);});
test('Result editor offers correct words for manual selection and existing destination decks',()=>{const d=fixture();deck(d);const html=refreshEditor(d,{selected:['w1'],merge:true,name:'<name>'},h);assert.match(html,/name="target"/);assert.match(html,/value="w1" checked/);assert.match(html,/value="w2" >/);assert.match(html,/&lt;name>/);assert.match(html,/refresh_r/);assert.match(refreshList(d,h),/2 offen/);});
test('Existing Google backend and replay preserve reference lists and personal appearance',()=>{const d=fixture(),r=deck(d),server=harness();const ops=[{id:'deck-op',entity:'settings',key:r.id,value:r,at:10,seq:1,device:'test'},{id:'theme-op',entity:'settings',key:'general',value:{accent:'blue',design:'minimal',density:'compact'},at:11,seq:2,device:'test'}];server.request({action:'push',base:0,ops});const pulled=server.request({action:'pull',since:0});assert.equal(pulled.data.settings.refresh_r.members[0].wordId,'w1');assert.equal(pulled.data.settings.general.accent,'blue');const restored=applyOps(d,ops);assert.equal(refreshDecks(restored).length,1);});
test('Compact collection view renders dropdown and separate reference tab without runtime errors',()=>{
 const d=fixture();deck(d);const source=fs.readFileSync(new URL('../app/main.js',import.meta.url),'utf8');
 const functions=['collectionsView','collectionLearningView','appearanceSettings','settingsView'].map(name=>source.split('\n').find(l=>l.startsWith('function '+name+'('))).join('\n');
 const ctx=vm.createContext({data:()=>d,collectionTab:'lessons',collectionFilter:'all',search:'',h,icon:()=>'',sharing:{toolbar:()=>''},sortedCollections,collectionActive,forgottenWords,refreshList,wordRows:()=>'<p>Wörter</p>',prefs:()=>({theme:'light',daily:10}),accountCard:()=>'',profile:{},updateView:()=>'',isAdmin:()=>false,APP_VERSION:'test'});vm.runInContext(functions,ctx);
 const lesson=vm.runInContext('collectionsView()',ctx);assert.match(lesson,/id="collection-select"/);assert.doesNotMatch(lesson,/class="collection-tabs"/);assert.ok(lesson.indexOf('Lektion 2')<lesson.indexOf('Lektion 10'));ctx.collectionTab='refresh';assert.match(vm.runInContext('collectionsView()',ctx),/Auffrischen 1–2/);const settings=vm.runInContext('settingsView()',ctx);for(const field of ['accent','density','design'])assert.match(settings,new RegExp('id="'+field+'"'));assert.match(settings,/<details/);
});
