import test from 'node:test';
import assert from 'node:assert/strict';
import {emptyData,progressFor} from '../app/core.js';
import {rateRefresh,refreshCardView,bindRefreshSwipe} from '../app/refresh-cards.js';
function fixture(){const data=emptyData();data.collections.a={id:'a',name:'Lektion 1'};for(const id of ['x','y','z'])data.words[id]={id,collectionId:'a',latin:id,meanings:[['eins','one'],['zwei']]};data.settings.r={id:'r',kind:'refreshDeck',name:'Meine Runde',members:[{wordId:'z',addedAt:1}]};return {data,session:{id:'s',mode:'inactive-check',refreshTarget:'r',sourceIds:['a'],queue:[{wordId:'x'},{wordId:'y'}],cursor:0,originalLength:2,cardFlipped:true}};}
function apply(data,result){for(const [entity,id,value] of result.ops)data[entity][id]=value;return result.session;}
test('Cards require flipping and record a secure self-assessment without typing',()=>{const {data,session}=fixture();assert.equal(rateRefresh(data,{...session,cardFlipped:false},true),null);const result=rateRefresh(data,session,true,10);assert.equal(session.cursor,0);assert.equal(result.session.cursor,1);assert.equal(result.session.cardFlipped,false);apply(data,result);assert.equal(progressFor('x',data.reviews).level,'known');assert.equal(data.settings.r.members.length,1);});
test('Last card automatically merges only unknown words into exact target in one commit',()=>{const {data,session}=fixture();const next=apply(data,rateRefresh(data,session,true,10));next.cardFlipped=true;const result=rateRefresh(data,JSON.parse(JSON.stringify(next)),false,20);assert.equal(result.session.finished,true);assert.equal(result.session.refreshSavedCount,1);assert.deepEqual(result.ops.map(o=>o[0]),['reviews','settings','sessions']);apply(data,result);assert.deepEqual(data.settings.r.members.map(m=>m.wordId),['z','y']);assert.equal(rateRefresh(data,result.session,false),null);});
test('All known preserves existing members; missing target is recreated; deleted words are skipped',()=>{const {data,session}=fixture();session.queue=[{wordId:'x'}];session.originalLength=1;let result=rateRefresh(data,session,true,10);assert.equal(result.session.refreshSavedCount,0);assert.deepEqual(result.ops.find(o=>o[0]==='settings')[2].members.map(m=>m.wordId),['z']);delete data.settings.r;result=rateRefresh(data,session,false,20);assert.equal(result.ops.find(o=>o[0]==='settings')[1],'r');assert.equal(result.session.refreshSavedCount,1);delete data.words.x;result=rateRefresh(data,{...session,cardFlipped:false},false);assert.equal(result.session.finished,true);assert.equal(result.session.refreshSavedCount,0);});
test('Card front hides translations; back shows every meaning and alternative',()=>{const {data,session}=fixture();const h=x=>x;const front=refreshCardView({...session,cardFlipped:false},data.words.x,h,()=> '');assert.doesNotMatch(front,/eins|one|zwei/);assert.match(front,/disabled/);const back=refreshCardView(session,data.words.x,h,()=> '');assert.match(back,/eins \/ one, zwei/);assert.doesNotMatch(back,/disabled/);assert.doesNotMatch(back,/answer-form|meaningRequirement/);});
test('Swipe direction, threshold, vertical scroll and cancellation are guarded',()=>{const listeners={},ratings=[];let flipped=true;const card={style:{},classList:{contains:()=>flipped},addEventListener:(n,fn)=>listeners[n]=fn,setPointerCapture(){}};bindRefreshSwipe(card,x=>ratings.push(x));const down=()=>listeners.pointerdown({isPrimary:true,button:0,pointerId:1,clientX:100,clientY:100});const up=(x,y=100)=>listeners.pointerup({pointerId:1,clientX:x,clientY:y});down();up(180);down();up(20);down();up(120);down();up(180,250);flipped=false;down();up(180);flipped=true;down();listeners.pointercancel();up(180);assert.deepEqual(ratings,[true,false]);});
