import {parseCollectionFile,importChanges} from './refresh-import.js';
import {rateRefresh,refreshCardView,bindRefreshSwipe,finishRefresh} from './refresh-cards.js';
import {sortedCollections,refreshDecks,wordEnabled,trainingDecks,wordsForDecks,deckMembers,pendingMembers,saveDeck,checkResultWords} from './refresh-decks.js';
import {refreshList,refreshMethod,collectionRow,collectionToolbar,refreshCreate,checkPicker,refreshEditor} from './refresh-ui.js';
import {activityKey,collectionActive,forgottenWords,inactiveQueue} from './collection-learning.js';
import {classroomView,classroomResults} from './classroom.js';
import {uid,clone,normalize,evaluateSession,progressFor,chooseWords,parseImport} from './core.js';
import {confusionUI} from './confusion-ui.js';
import {openAccount,signOut,accountCard} from './accounts.js';
import {sharingUI} from './sharing-ui.js';
import {cloudGate,settleSync,unreadShareNotices} from './multiuser-sync.js';
import {Sync} from './sync.js';
import {answerFeedback,translationCard} from './feedback.js';
import {AppUpdates,APP_VERSION} from './updates.js';
const updates=new AppUpdates(navigator.serviceWorker);
const h=text=>String(text??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const icons={home:'<path d="m3 10 9-7 9 7v10a1 1 0 0 1-1 1h-5v-7H9v7H4a1 1 0 0 1-1-1z"/>',book:'<path d="M12 6c-3-3-7-3-10-2v15c4-1 7 0 10 2 3-2 6-3 10-2V4c-3-1-7-1-10 2zM12 6v15"/>',settings:'<path d="M12 8a4 4 0 1 0 0 8 4 4 0 0 0 0-8zM9 3l-1 3-3 1-2 3 2 2-1 3 3 3 3-1 2 3 3-1 1-3 3-1 2-3-2-2 1-3-3-3-3 1-2-3z"/>',cloud:'<path d="M7 18H6a4 4 0 0 1-.5-8A7 7 0 0 1 19 9a4.5 4.5 0 0 1-1 9h-1M12 20V11m-3 3 3-3 3 3"/>',check:'<path d="m5 12 4 4L19 6"/>',arrow:'<path d="M5 12h14m-5-5 5 5-5 5"/>',plus:'<path d="M12 5v14M5 12h14"/>',close:'<path d="m6 6 12 12M6 18 18 6"/>',edit:'<path d="m14 5 5 5M4 20l5-1L21 7a2 2 0 0 0-4-4L5 15z"/>',trash:'<path d="M3 6h18M9 6V3h6v3M5 6l1 15h12l1-15M10 10v7m4-7v7"/>',sun:'<circle cx="12" cy="12" r="4"/><path d="M12 1v2m0 18v2M1 12h2m18 0h2M4 4l2 2m12 12 2 2M4 20l2-2M18 6l2-2"/>',moon:'<path d="M20 15A9 9 0 0 1 9 3a9 9 0 1 0 11 12z"/>',target:'<circle cx="12" cy="12" r="9"/><circle cx="12" cy="12" r="5"/><circle cx="12" cy="12" r="1"/>',award:'<circle cx="12" cy="8" r="6"/><path d="m8 13-2 9 6-3 6 3-2-9"/>',repeat:'<path d="M3 7h13a5 5 0 0 1 5 5M7 3 3 7l4 4M21 17H8a5 5 0 0 1-5-5m14 1 4 4-4 4"/>',search:'<circle cx="10" cy="10" r="6"/><path d="m15 15 6 6"/>',download:'<path d="M12 3v12m-5-5 5 5 5-5M4 16v5h16v-5"/>',upload:'<path d="M12 16V4m-5 5 5-5 5 5M4 16v5h16v-5"/>',bolt:'<path d="m13 2-9 12h7l-1 8 10-13h-8z"/>',info:'<circle cx="12" cy="12" r="9"/><path d="M12 11v6m0-10v1"/>'};
const icon=(name,cls='')=>`<svg class="icon ${cls}" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${icons[name]||icons.book}</svg>`;
const openPanels=new Set();
let collectionTab='lessons',refreshFlow=null;
let profile,sharing,cloudWait,ready=false,store,sync,confusions,screen='learn',classroomQuery='',collectionFilter='all',search='',selected=[],modalCleanup=null,toastTimer,working=false;
const app=document.querySelector('#app'),modalRoot=document.querySelector('#modal-root');
const isAdmin=()=>profile?.role==='admin';
const data=()=>store.data;
function autoUpdate(){if(ready&&updates.state==='available'&&!working&&!cloudWait?.blocked&&!modalRoot.children.length&&!['test','match'].includes(screen)&&!sync.busy&&!sharing?.busy&&!store.doc.pending.length)void updates.apply();}
async function showResult(){const saved=store.doc.session;if(saved?.mode==='inactive-check'&&saved.finished&&saved.refreshSavedCount===undefined){const session=clone(saved);await store.commit([finishRefresh(data(),session)],session);sync.schedule(0);}await cloudWait.run('Fortschritt wird hochgeladen …');screen='result';render();}
async function backgroundSync(){if(working||cloudWait?.blocked||['test','match'].includes(screen)||modalRoot.children.length){sync.schedule(0);return;}try{await settleSync(sync,store);if(unreadShareNotices(data()).length&&!working&&!modalRoot.children.length&&!['test','match'].includes(screen))await loadCloud();if(!working&&!modalRoot.children.length&&!['test','match'].includes(screen))render();}catch{} }

const prefs=()=>({daily:10,typos:true,...data().settings.general,theme:'system',accent:'green',density:'comfortable',design:'rounded'});
const allWords=()=>Object.values(data().words).filter(w=>data().collections[w.collectionId]);
const activeWords=()=>wordsForDecks(data(),trainingDecks(data()).filter(d=>d.active).map(d=>d.id));
function notify(message){const el=document.querySelector('#toast');el.textContent=message;el.classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.classList.remove('visible'),4500);}
function theme(){const p=prefs();document.documentElement.dataset.theme=p.theme==='system'?(matchMedia('(prefers-color-scheme: dark)').matches?'dark':'light'):p.theme;document.documentElement.dataset.accent=p.accent||'green';document.documentElement.dataset.density=p.density||'comfortable';document.documentElement.dataset.design=p.design||'rounded';}
function nav(){return `<nav aria-label="Hauptmenü">${[['learn','home','Lernen'],['collections','book','Sammlungen'],['classroom','search','Unterricht'],['settings','settings','Einstellungen']].map(([id,i,label])=>`<button data-action="nav" data-screen="${id}" class="nav-item ${(screen===id||id==='collections'&&screen==='collection-detail')?'active':''}" ${screen===id?'aria-current="page"':''}>${icon(i)}<span>${label}</span></button>`).join('')}</nav>`;}
function todayCount(){const today=new Date().toLocaleDateString('sv');return Object.values(data().reviews).filter(r=>!r.repeat&&!r.manualKnown&&new Date(r.at).toLocaleDateString('sv')===today).length;}
function statusMarkup(){const doc=store.doc;const label=({checking:'Cloud wird geprüft',loading:'Cloud wird geladen',uploading:'Wird gespeichert',synced:'Gespeichert',newer:'Cloud wird geladen',offline:'Offline',error:'Verbindung prüfen'})[sync.status]||'Cloud';return `<button class="sync-indicator ${sync.status}" data-action="sync-info" title="${h(label)}">${icon('cloud',sync.busy?'pulse':'')}<span>${h(label)}</span></button>`;}
function updateStatus(){setTimeout(autoUpdate,0);document.querySelectorAll('[data-sync]').forEach(el=>el.innerHTML=statusMarkup());const detail=document.querySelector('[data-sync-details]');if(detail)detail.innerHTML=syncDetails();}
function render(){theme();if(screen==='match'){app.innerHTML=confusions.view();return;}if(screen==='test'){renderTest();return;}if(screen==='result'){renderResult();return;}
  app.innerHTML=`<aside class="sidebar"><a class="brand" href="#" data-action="nav" data-screen="learn">latinio<span>✦</span></a>${nav()}<div class="sidebar-foot"><div class="language-tag">LA <span>→</span> DE</div><p>Ein bisschen Latein.<br>Jeden Tag.</p><span class="muted small">App ${APP_VERSION}</span></div></aside><div class="workspace"><header class="topbar"><span class="mobile-brand brand">latinio<span>✦</span></span><span class="desktop-only muted">Dein Lateintraining</span></header><main class="content">${!isAdmin()?'<p class="small muted">Aktivitätsprotokoll für deine Lehrkraft aktiv: Uhrzeit und allgemeine Aktionen, keine Wörter oder Antworten. Details unter Einstellungen.</p>':''}${screen==='learn'?learnView():screen==='collections'?collectionsView():screen==='collection-detail'?collectionDetailView():screen==='classroom'?classroomView(data(),classroomQuery,h):settingsView()}</main></div><div class="mobile-nav">${nav()}</div>`;
 app.querySelectorAll('details[data-panel]').forEach(el=>{el.open=openPanels.has(el.dataset.panel);});
}
function learnView(){const d=data(),words=activeWords();const known=words.filter(w=>progressFor(w.id,d.reviews).level==='known').length;const due=words.filter(w=>{const p=progressFor(w.id,d.reviews);return p.seen&&p.due<=Date.now();}).length;const count=todayCount(),goal=prefs().daily;const decks=trainingDecks(d).filter(x=>x.active);selected=selected.filter(id=>decks.some(x=>x.id===id));if(!selected.length)selected=decks.map(x=>x.id);
 return `<div class="page-heading"><div><div class="eyebrow">DEIN SMARTES TRAINING</div><h1>Hallo ${h(isAdmin()?'Tiago':profile.name)}!</h1><p class="muted" data-compact-hide>Kleine Schritte. Immer mehr im Kopf.</p></div><div class="daily-badge">${icon('bolt')}<strong>${count}</strong><span>heute</span></div></div>
 <div class="learning-grid"><div class="primary-column"><section class="training-card"><div class="section-top"><span class="tag">LATEIN → DEUTSCH</span>${icon('book','large-icon')}</div><h2>Das weißt du bald<br>wieder.</h2><p data-compact-hide>Übe neue Wörter und frische auf,<br>was noch nicht ganz sitzt.</p><details data-panel="home-decks" class="deck-picker"><summary>Trainingsauswahl · ${decks.length} aktive Sammlungen</summary><div class="bounded-list">${decks.map(c=>`<label class="collection-check"><input type="checkbox" data-select="${h(c.id)}" ${selected.includes(c.id)?'checked':''}><span>${h(c.name)}</span><small>${wordsForDecks(d,[c.id]).length} Wörter</small></label>`).join('')||'<p>Keine aktive Sammlung. Schalte unter Sammlungen die gewünschten Lektionen ein.</p>'}</div></details><div class="word-tools"><button class="button primary wide" data-action="start" ${!words.length?'disabled':''}>Smartes Üben ${icon('arrow')}</button><button class="button secondary wide" data-action="training-options" ${!words.length?'disabled':''}>Mehr Optionen ${icon('plus')}</button></div>${store.doc.session&&!store.doc.session.finished?'<p class="small muted">Deine angefangene Runde wird fortgesetzt.</p>':''}<div class="card-foot">${icon('target')} ${goal} Wörter pro Runde · beliebig weiterüben</div></section>
 <section class="progress-section"><div class="section-top"><h2>Dein Wortschatz wächst</h2><span class="muted small">${words.length} Vokabeln</span></div><div class="stats-row"><div class="stat"><span class="stat-icon green">${icon('check')}</span><strong>${known}</strong><span>Schon sicher</span></div><div class="stat"><span class="stat-icon purple">${icon('repeat')}</span><strong>${words.filter(w=>progressFor(w.id,d.reviews).level==='learning').length}</strong><span>Im Training</span></div><div class="stat"><span class="stat-icon orange">${icon('book')}</span><strong>${words.filter(w=>!progressFor(w.id,d.reviews).seen).length}</strong><span>Noch neu</span></div></div></section></div>
 <aside class="secondary-column"><section class="card goal-card"><div class="section-top"><h3>Dein Tagesziel</h3>${icon('target')}</div><div class="goal-ring" style="--progress:${Math.min(100,count/goal*100)}%"><div><strong>${count}<span> / ${goal}</span></strong><small>Vokabeln</small></div></div><p>${count>=goal?'Tagesziel geschafft. Bene!':'Ein guter Tag für einen kleinen Fortschritt.'}</p></section><section class="card reminder-card"><span class="stat-icon purple">${icon('repeat')}</span><h3>${due?`${due} Wörter sind wieder dran`:'Wiederholen, wenn es zählt'}</h3><p class="muted" data-compact-hide>Unsichere Wörter öfter wiederholen.</p></section><button class="card collection-link" data-action="nav" data-screen="collections"><span>${icon('book')} Deine Sammlungen</span>${icon('arrow')}</button></aside></div>`;
}
function collectionsView(){const d=data();return `<div class="page-heading"><h1>Sammlungen</h1></div><label class="search-field collection-search">${icon('search')}<input id="search" placeholder="Alle Vokabeln durchsuchen" value="${h(search)}" aria-label="Vokabel suchen"></label><section id="collection-search-results" class="bounded-list">${search.trim()?wordRows('all',search):''}</section><div class="button-row section-tabs"><button class="chip ${collectionTab==='lessons'?'selected':''}" data-action="collection-tab" data-id="lessons">Lektionen</button><button class="chip ${collectionTab==='refresh'?'selected':''}" data-action="collection-tab" data-id="refresh">Auffrischen</button></div>${collectionTab==='refresh'?refreshList(d,h,icon):collectionLearningView(d)}<div class="collection-footer">${sharing.toolbar()}<button class="button secondary" data-action="confusion-manage">Verwechslungen verwalten</button></div>`;}
function collectionLearningView(d){return `<section class="card collection-learning">${collectionToolbar()}<div class="bounded-list">${sortedCollections(d).map(c=>collectionRow(c,collectionActive(d,c.id),false,h,icon)).join('')||'<p class="muted">Noch keine Lektionen.</p>'}</div></section>`;}
function collectionDetailView(){const c=data().collections[collectionFilter]||data().settings[collectionFilter],refresh=c?.kind==='refreshDeck';if(!c)return '<p>Sammlung nicht mehr vorhanden.</p><button class="button secondary" data-action="nav" data-screen="collections">Zurück</button>';return `<button class="text-button" data-action="nav" data-screen="collections">← Sammlungen</button><div class="page-heading collection-detail-heading"><div class="collection-title"><h1>${h(c.name)}</h1><button class="icon-button" data-action="rename-collection" data-id="${h(c.id)}" aria-label="Sammlung umbenennen">${icon('edit')}</button></div><button class="button primary" data-action="${refresh?'check-picker':'new-word'}" data-id="${h(c.id)}">${icon('plus')} Vokabeln hinzufügen</button></div><button class="text-button danger-text" data-action="${refresh?'refresh-delete':'delete-collection'}" data-id="${h(c.id)}">Sammlung löschen</button><label class="search-field collection-search">${icon('search')}<input id="search" placeholder="In dieser Sammlung suchen" value="${h(search)}" aria-label="Vokabel suchen"></label><section class="word-list" id="word-list">${wordRows()}</section>`;}
async function setActivity(ids,active){
 const changed=ids.filter(id=>collectionActive(data(),id)!==active);
 if(!changed.length){render();return;}
 const s=store.doc.session;
 const affected=!active&&s&&!s.finished&&!s.mode?.startsWith('inactive-')&&s.queue.slice(s.cursor).some(x=>changed.includes(data().words[x.wordId]?.collectionId));
 const matchAffected=!active&&store.doc.matchRound?.words.some(w=>changed.includes(w.collectionId));
 if((affected||matchAffected)&&!confirm('Eine angefangene Runde enthält diese Sammlung und wird beendet. Bereits gespeicherte Antworten bleiben erhalten. Fortfahren?')){render();return;}
 await store.commit(changed.map(id=>['settings',activityKey(id),{kind:'collectionActivity',active}]));
 if(affected||matchAffected)await store.update(doc=>{if(affected)doc.session=null;if(matchAffected)doc.matchRound=null;return doc;});
 selected=selected.filter(id=>collectionActive(data(),id));sync.schedule();render();
}
function wordRows(filter=collectionFilter,query=search){const d=data(),deck=d.settings[filter]?.kind==='refreshDeck'?d.settings[filter]:null,members=new Set(deckMembers(d,deck).map(m=>m.wordId)),pending=new Set(pendingMembers(d,deck).map(m=>m.wordId));const items=allWords().filter(w=>(deck?members.has(w.id):filter==='all'||w.collectionId===filter)&&normalize(w.latin+' '+w.meanings.flat().join(' ')).includes(normalize(query)));return items.map(w=>{const p=progressFor(w.id,d.reviews),level=deck&&!pending.has(w.id)?'known':p.level;return `<article class="word-row"><div><strong>${h(w.latin)}</strong><span class="small muted">${h(d.collections[w.collectionId]?.name)}</span></div><p>${w.meanings.map(g=>h(g.join(' / '))).join(' · ')}</p><span class="word-level ${level}">${{new:'Neu',learning:'Im Training',known:'Sicher'}[level]}${deck&&pending.has(w.id)?' · Offen':''}</span><button class="icon-button" aria-label="${h(w.latin)} ${deck?'aus Auffrisch-Sammlung entfernen':'bearbeiten'}" data-action="${deck?'refresh-remove-word':'edit-word'}" data-id="${h(w.id)}">${icon(deck?'trash':'edit')}</button></article>`;}).join('')||'<div class="empty-state"><p class="muted">Keine Vokabeln gefunden.</p></div>';}
function syncDetails(){const doc=store.doc;return `<div class="sync-box"><p class="sync-state">${icon('cloud')} ${h(sync.message)}</p><dl><div><dt>Bestätigter Gerätestand</dt><dd>v${doc.base}</dd></div><div><dt>Cloud-Version</dt><dd>${sync.cloudVersion===null?'Noch nicht geprüft':'v'+sync.cloudVersion}</dd></div><div><dt>Lokale Änderungen</dt><dd>${doc.pending.length} ausstehend</dd></div><div><dt>Lokaler Änderungszähler</dt><dd>${doc.seq}</dd></div><div><dt>Letzter Abgleich</dt><dd>${doc.lastSync?h(new Date(doc.lastSync).toLocaleString('de-DE')):'Noch keiner'}</dd></div></dl>${sync.busy?'<div class="indeterminate" role="progressbar" aria-label="Synchronisierung läuft"></div>':''}</div>`;}
function updateView(){const busy=['checking','installing'].includes(updates.state);return `<h2>App-Updates</h2><p class="small muted">Installierte Version: ${APP_VERSION}</p><p role="status" class="update-message">${h(updates.message)}</p><button type="button" class="button ${updates.state==='available'?'primary':'secondary'} wide" data-action="${updates.state==='available'?'apply-update':'check-update'}" ${busy?'disabled':''}>${icon('repeat')} ${updates.state==='available'?'Jetzt aktualisieren':busy?'Bitte warten …':'Nach Updates suchen'}</button>`;}
updates.addEventListener('change',()=>{const area=document.querySelector('[data-app-updates]');if(area)area.innerHTML=updateView();autoUpdate();});
function settingsView(){const p=prefs();return `<div class="page-heading"><div><div class="eyebrow">SO LERNST DU</div><h1>Einstellungen</h1><p class="muted" data-compact-hide>Dein Tempo. Deine App.</p></div></div><div class="settings-grid">${accountCard(profile)}<details data-panel="updates" class="card compact-panel"><summary>App-Updates</summary><div data-app-updates>${updateView()}</div></details><details data-panel="appearance" class="card compact-panel"><summary>Training</summary><label class="setting-row"><span><strong>Tagesziel</strong><small data-compact-hide>Rundengröße und Tagesziel · kein Tageslimit</small></span><select id="daily">${[5,10,15,20,30].map(n=>`<option value="${n}" ${p.daily===n?'selected':''}>${n} Wörter</option>`).join('')}</select></label><label class="setting-row"><span><strong>Tippfehler tolerieren</strong><small data-compact-hide>Einen kleinen Schreibfehler erkennen.<br>Du kannst jede Bewertung korrigieren.</small></span><input class="switch" id="typos" type="checkbox" ${p.typos?'checked':''}></label></details><details data-panel="import" class="card compact-panel"><summary>Vokabeln & Installation</summary><button class="button secondary wide" data-action="import">${icon('upload')} Sammlung importieren</button><button class="text-button" data-action="download-example">Beispiel für das Importformat</button><div class="divider"></div><h3>Auf deinem iPhone</h3><p class="muted">Safari → Teilen → Zum Home-Bildschirm.</p></details>${isAdmin()?`<details data-panel="cloud" class="card cloud-settings compact-panel"><summary>Cloud & Versionen</summary><div data-sync-details>${syncDetails()}</div><div class="button-row"><button class="button secondary" data-action="sync-now" ${!sync.configured?'disabled':''}>${icon('repeat')} Jetzt abgleichen</button>${sync.remote?'<button class="button primary" data-action="remote">Cloud-Version ansehen</button>':''}</div></details>`:''}</div><p class="small muted app-version">Latinio ${APP_VERSION} · Immer Latein → Deutsch</p>`;}
function showModal(content){const previous=document.activeElement;modalCleanup?.();modalRoot.innerHTML=`<div class="modal-overlay"><section role="dialog" aria-modal="true" class="modal" aria-labelledby="modal-title"><button class="icon-button modal-close" data-action="close-modal" aria-label="Schließen">${icon('close')}</button>${content}</section></div>`;
  const listener=e=>{if(cloudWait?.blocked)return;if(e.key==='Escape')closeModal();if(e.key==='Tab'){const nodes=[...modalRoot.querySelectorAll('button,input,select,textarea,a[href]')].filter(n=>!n.disabled);const first=nodes[0],last=nodes.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus();}}};document.addEventListener('keydown',listener);modalCleanup=()=>{document.removeEventListener('keydown',listener);previous?.focus();};modalRoot.querySelector('input,select,button')?.focus();}
function closeModal(){modalRoot.innerHTML='';modalCleanup?.();modalCleanup=null;}
function remoteContent(){const comparison=sync.compare();const conflicts=comparison.conflicts;return `<span class="stat-icon purple">${icon('cloud')}</span><h2 id="modal-title">Eine neuere Version ist da.</h2><p>Auf diesem Gerät: <strong>v${store.doc.base}</strong><br>In deiner Cloud: <strong>v${sync.remote.version}</strong></p><p class="muted">${store.doc.pending.filter(o=>!o.bootstrap).length?'Deine ausstehenden Änderungen bleiben erhalten. Bearbeitungen derselben Angabe vergleichst du unten.':'Lade den aktuellen Stand, um hier weiterzulernen.'}</p><form id="remote-form">${conflicts.map((c,i)=>`<div class="conflict"><h3>${h(conflictName(c.local))}</h3><p><strong>Dieses Gerät:</strong> ${h(conflictValue(c.local.value))}</p><p><strong>Cloud:</strong> ${h(conflictValue(c.remote.value))}</p><label>Welche Fassung soll bleiben?<select name="c${i}" data-conflict="${h(c.key)}" required><option value="">Bitte wählen</option><option value="local">Dieses Gerät</option><option value="cloud">Cloud</option></select></label></div>`).join('')}<button type="submit" class="button primary wide">${icon('download')} Cloud-Version laden${conflicts.length?' & zusammenführen':''}</button></form>`;}
function remoteModal(){if(!sync.remote)return;showModal(remoteContent());}
function conflictName(op){return op.value?.latin||op.value?.name||data().words[op.key]?.latin||'Geänderte Angabe';}
function conflictValue(value){if(value===null)return 'Gelöscht';if(value.latin)return value.latin+' – '+value.meanings.map(g=>g.join(' / ')).join(', ');if(value.name)return value.name;if(value.grade)return 'Bewertung: '+value.grade;return JSON.stringify(value);}
function wordModal(id){const d=data(),word=d.words[id]||{id:uid(),collectionId:collectionFilter!=='all'?collectionFilter:Object.keys(d.collections)[0],latin:'',meanings:[['']]};if(!word.collectionId){notify('Lege zuerst eine Sammlung an.');return;}
 showModal(`<h2 id="modal-title">${id?'Vokabel bearbeiten':'Neue Vokabel'}</h2><form id="word-form" data-id="${h(word.id)}"><label>Sammlung<select name="collectionId">${[...sortedCollections(d),...(d.collections[word.collectionId]?.refreshSource?[d.collections[word.collectionId]]:[])].map(c=>`<option value="${h(c.id)}" ${word.collectionId===c.id?'selected':''}>${h(c.name)}</option>`).join('')}</select></label><label>Latein · alle angezeigten Formen<input name="latin" required maxlength="200" value="${h(word.latin)}" placeholder="vox, vocis"></label><label>Deutsche Bedeutungen</label><div id="meaning-inputs">${word.meanings.map(g=>meaningInput(g.join(' / '))).join('')}</div><button type="button" class="text-button" data-action="add-meaning">${icon('plus')} Bedeutung hinzufügen</button><p class="small muted" data-compact-hide>Eine Bedeutung pro Feld. Alternativen mit / trennen.</p><details><summary>Zusätzliche Suchformen (optional)</summary><label>Nur für den Vokabelsucher, mit Komma trennen<input name="forms" value="${h((word.forms||[]).join(', '))}" maxlength="10000" placeholder="z. B. vocem, voces, vocibus"></label></details><div class="button-row"><button type="submit" class="button primary">Speichern</button>${id?`<button type="button" class="button danger" data-action="delete-word" data-id="${h(id)}">${icon('trash')} Löschen</button>`:''}</div></form>`);}
function meaningInput(value=''){return `<div class="meaning-input"><input name="meaning" value="${h(value)}" required maxlength="300" aria-label="Deutsche Bedeutung"><button type="button" class="icon-button" data-action="remove-meaning" aria-label="Bedeutung entfernen">${icon('close')}</button></div>`;}
function importModal(){showModal(`<h2 id="modal-title">Eine neue Sammlung</h2><p class="muted" data-compact-hide>Normale Sammlung oder Auffrisch-Datei auswählen. Das Dateiformat bestimmt den Zielbereich.</p><label class="file-drop">${icon('upload')}<strong>JSON-Datei auswählen</strong><input type="file" id="import-file" accept=".json,application/json"></label><div id="import-preview"></div>`);}
let importCandidate=null;
function trainingOptions(){
 const words=wordsForDecks(data(),selected);
 const learning=words.filter(w=>progressFor(w.id,data().reviews).level!=='known').length;
 const known=words.length-learning;
 showModal(`<h2 id="modal-title">Mehr Optionen</h2><p class="muted">Für deine Trainingsauswahl.</p><div class="word-tools"><button class="button secondary wide" data-action="start-refresh" ${!known?'disabled':''}>Auffrischen · ${known} sichere Wörter</button><button class="button secondary wide" data-action="start-learning" ${!learning?'disabled':''}>Noch unsichere Wörter üben · ${learning}</button><button class="button secondary wide" data-action="start-all" ${!words.length?'disabled':''}>Alle ausgewählten Vokabeln üben · ${words.length}</button></div>`);
}
async function start(mode='smart',ids=selected,refreshTarget=null){
 
 await cloudWait.run('Wir bereiten alles vor.');
 // A different device may have deactivated a collection since this round began.
 const saved=store.doc.session;
 if(saved&&!saved.finished&&!saved.mode?.startsWith('inactive-')&&saved.queue.slice(saved.cursor).some(x=>!wordEnabled(data(),x.wordId))){
  await store.update(doc=>{doc.session=null;return doc;});notify('Die pausierte Runde enthielt inzwischen inaktive Sammlungen. Gespeicherte Antworten bleiben erhalten.');
 }
 if(store.doc.matchRound?.words.some(w=>!collectionActive(data(),w.collectionId)))await store.update(doc=>{doc.matchRound=null;return doc;});
 if(mode==='inactive-check'&&((store.doc.session&&!store.doc.session.finished)||store.doc.matchRound)){
  if(!confirm('Die pausierte Runde beenden und diesen Test starten? Gespeicherte Antworten bleiben erhalten.'))return;
  await store.update(doc=>{doc.session=null;doc.matchRound=null;return doc;});
 }
 if(store.doc.matchRound){closeModal();screen='match';render();return;}
 if(store.doc.session&&!store.doc.session.finished){closeModal();screen='test';render();return;}
 if(!ids.length&&!mode.startsWith('inactive-')){notify('Wähle mindestens eine Sammlung aus.');return;}
 const queue=mode.startsWith('inactive-')?inactiveQueue(data(),ids,mode,prefs().daily):chooseWords(data(),ids,prefs().daily,mode);
 if(!queue.length){notify(mode==='refresh'?'In dieser Auswahl sind noch keine sicheren Vokabeln zum Auffrischen.':mode==='learning'?'Diese Vokabeln sind schon sicher. Nutze Auffrischen oder wiederhole alle.':'In dieser Auswahl sind keine Vokabeln.');return;}
 closeModal();
 const session={id:uid(),mode,sourceIds:ids,refreshTarget,cardFlipped:false,queue:queue.map(wordId=>({wordId,repeat:false})),cursor:0,originalLength:queue.length,answers:[''],feedback:null,overrides:{},startedAt:Date.now(),finished:false};
 await store.update(doc=>{doc.session=session;return doc;});await store.recordActivity?.('started');sync.schedule();screen='test';render();
}
function current(){const session=store.doc.session;if(!session)return {};const item=session.queue[session.cursor];return {session,item,word:data().words[item?.wordId]};}
function renderTest(){const {session,item,word}=current();if(!session){screen='learn';render();return;}if(!word){app.innerHTML=`<main class="test-shell"><h1>Diese Vokabel wurde gelöscht.</h1><button class="button primary" data-action="next">Weiter</button></main>`;return;}
 if(session.mode==='inactive-check'){app.innerHTML=refreshCardView(session,word,h,icon);const cursor=session.cursor;bindRefreshSwipe(app.querySelector('.refresh-card'),known=>{void actions({preventDefault(){},target:{closest:()=>({dataset:{action:known?'refresh-card-known':'refresh-card-wrong',cursor:String(cursor)}})}});});return;}
 const feedback=session.feedback;const pct=Math.round(session.cursor/session.queue.length*100);
 app.innerHTML=`<main class="test-shell"><header class="test-top"><button class="icon-button" data-action="pause" aria-label="Runde pausieren">${icon('close')}</button><div class="test-progress"><div style="width:${pct}%"></div></div><span class="small muted">${session.cursor+1} / ${session.queue.length}</span></header><div class="test-content"><div class="eyebrow">${item.repeat?'NOCH EINMAL FESTIGEN':'LATEIN → DEUTSCH'}</div><div class="test-title"><h1>Was bedeutet …</h1><button class="icon-button" data-action="edit-word" data-id="${h(word.id)}" aria-label="Vokabel bearbeiten">${icon('edit')}</button></div>${session.mode==='inactive-check'?`<p class="small muted">${session.meaningRequirement==='any'?'Eine Bedeutung reicht':'Alle Bedeutungen erforderlich'}</p>`:''}<div class="latin-word" lang="la">${h(word.latin)}</div>${translationCard(word,feedback)}${!feedback?'<p class="muted test-help" data-compact-hide>Schreibe die Bedeutungen auf, die du kennst.</p>':''}<form id="answer-form"><div id="answers">${feedback?answerFeedback(feedback):session.answers.map((a,i)=>answerInput(a,i,false)).join('')}</div>${!feedback?`<button type="button" class="add-answer" data-action="add-answer">${icon('plus')} Weitere Bedeutung</button>`:''}<div class="test-feedback">${feedback?feedbackView(word,feedback)+confusions.prompt(word,feedback,session):''}</div><footer class="test-footer ${feedback?'compact-footer':''}">${feedback?`<button class="button primary wide" type="button" data-action="next">Weiter ${icon('arrow')}</button>`:`<button class="text-button" type="button" data-action="dont-know">Weiß ich noch nicht</button><button class="button primary" type="submit">Prüfen ${icon('check')}</button>`}</footer></form></div></main>`;
 if(!feedback)document.querySelector('#answers input')?.focus({preventScroll:true});
}
function answerInput(value,i,disabled){return `<div class="answer-row"><span>${i+1}</span><input name="answer" value="${h(value)}" placeholder="Deutsche Bedeutung" aria-label="Deutsche Bedeutung ${i+1}" lang="de" inputmode="text" autocomplete="on" autocorrect="on" autocapitalize="sentences" spellcheck="true" maxlength="300" ${disabled?'readonly':''}>${!disabled&&i>0?`<button type="button" class="icon-button" data-action="remove-answer" data-index="${i}" aria-label="Antwortfeld entfernen">${icon('close')}</button>`:''}</div>`;}
function feedbackView(word,f){const title={full:f.meaningRequirement==='any'?'Bedeutung erkannt!':'Alles richtig!',partial:'Richtig – noch nicht vollständig.',wrong:'Noch nicht ganz.'}[f.grade];return `<section class="feedback compact-feedback ${f.grade}" aria-live="polite"><h2>${icon(f.grade==='wrong'?'repeat':'check')} ${title}</h2><button type="button" class="icon-button" data-action="edit-word" data-id="${h(word.id)}" aria-label="Vokabeleintrag korrigieren">${icon('edit')}</button></section>`;}

function readAnswers(){return [...document.querySelectorAll('#answers input')].map(el=>el.value);}
async function checkAnswer(skip=false){const {session,word,item}=current();if(!word||session.feedback)return;session.answers=readAnswers();if(skip)session.answers=[''];session.overrides={};session.feedback=evaluateSession(word,session.answers,prefs().typos,{},session);const review={id:session.id+'-'+session.cursor,wordId:word.id,grade:session.feedback.grade,at:Date.now(),repeat:item.repeat,mode:session.mode||'smart',meaningRequirement:session.meaningRequirement||'all',answers:session.answers};await store.commit([['reviews',review.id,review]],session);sync.schedule();render();}
async function reevaluate(){const {session,word}=current();if(!session.feedback||!word)return;session.feedback=evaluateSession(word,session.answers,prefs().typos,session.overrides,session);const key=session.id+'-'+session.cursor;const review={...data().reviews[key],grade:session.feedback.grade,answers:session.answers};await store.commit([['reviews',key,review]],session);sync.schedule();render();}
async function next(){const {session,item,word}=current();if(!session)return;
 if(session.mode==='inactive-check'){await rateCard(false);return;}
 if(word&&!session.feedback)return;
 if(session.feedback&&session.feedback.grade!=='full'&&!item.repeat&&session.mode!=='inactive-check')session.queue.push({wordId:item.wordId,repeat:true});
 session.cursor++;session.answers=[''];session.feedback=null;session.overrides={};
 if(session.cursor>=session.queue.length){session.finished=true;await store.commit([['sessions',session.id,{id:session.id,at:Date.now(),count:session.originalLength}]],session);sync.schedule(0);if(!session.mode?.startsWith('inactive-')&&await confusions.offer(session.queue.map(x=>x.wordId)))return;await showResult();return;}else await store.update(doc=>{doc.session=session;return doc;});render();}
async function rateCard(known){const transition=rateRefresh(data(),store.doc.session,known);if(!transition)return;await store.commit(transition.ops,transition.session);sync.schedule(0);if(transition.session.finished)await showResult();else render();}
function renderResult(){const s=store.doc.session;if(!s){screen='learn';render();return;}const reviews=Object.values(data().reviews).filter(r=>r.id.startsWith(s.id+'-')&&!r.repeat);app.innerHTML=`<main class="result-shell"><div data-sync>${statusMarkup()}</div><span class="result-award">${icon('award')}</span><div class="eyebrow">RUNDE GESCHAFFT</div><h1>Ein Stück mehr<br>im Kopf.</h1><p class="muted">${s.originalLength} Vokabeln geübt. Gespeichert.</p><div class="result-stats">${[['full',s.mode==='inactive-check'?'Gewusst':'Ganz gewusst'],['partial','Teilweise gewusst'],['wrong','Wiederholen']].map(([grade,label])=>`<div class="${grade}"><strong>${reviews.filter(r=>r.grade===grade).length}</strong><span>${label}</span></div>`).join('')}</div>${s.mode==='inactive-check'?`<p class="muted">${s.refreshSavedCount??0} nicht gewusste Wörter automatisch in „${h(data().settings[s.refreshTarget]?.name||'Auffrisch-Sammlung')}“ gespeichert.</p>`:''}<p class="small muted" data-compact-hide>Die erste Antwort zählt.</p><button class="button primary wide" data-action="finish">Zur Übersicht ${icon('arrow')}</button></main>`;}
async function changePrefs(changes){await store.commit([['settings','general',{...prefs(),...changes}]]);sync.schedule();render();}
async function actions(event){const button=event.target.closest('[data-action]');if(!button)return;event.preventDefault();const action=button.dataset.action,id=button.dataset.id;
 if(!ready||working||cloudWait?.blocked)return;working=true;
 try{if(await sharing.handle(button))return;if(await confusions.handle(button))return;switch(action){
 case 'collection-open':collectionFilter=id;search='';screen='collection-detail';render();break;
 case 'collection-tab':collectionTab=id;render();break;
 case 'refresh-new':showModal(refreshCreate());break;
 case 'check-picker':refreshFlow={target:id,sourceIds:[]};showModal(checkPicker(data(),h,id));break;
 case 'refresh-select-back':showModal(checkPicker(data(),h,refreshFlow.target,refreshFlow.sourceIds));break;
 case 'refresh-select-manual':showModal(refreshEditor(data(),{id:refreshFlow.target,merge:true,sourceIds:refreshFlow.sourceIds},h));break;
 case 'refresh-select-test':await start('inactive-check',refreshFlow.sourceIds,refreshFlow.target);break;
 case 'refresh-card-flip':{const {session}=current();if(session?.mode!=='inactive-check'||session.finished)break;await store.update(doc=>{doc.session.cardFlipped=!doc.session.cardFlipped;return doc;});render();break;}
 case 'refresh-card-known':case 'refresh-card-wrong':if(String(current().session?.cursor)===button.dataset.cursor)await rateCard(action==='refresh-card-known');break;
 case 'refresh-remove-word':{const deck=data().settings[collectionFilter];if(deck?.kind!=='refreshDeck')break;await store.commit([['settings',deck.id,{...deck,members:deck.members.filter(m=>m.wordId!==id)}]]);sync.schedule();render();break;}
 case 'refresh-tools':collectionFilter=id;search='';screen='collection-detail';render();break;
 case 'refresh-activity-all':{const active=button.dataset.active==='true';const edits=refreshDecks(data()).filter(d=>(d.active!==false)!==active).map(d=>['settings',d.id,{...d,active}]);if(edits.length)await store.commit(edits);sync.schedule();render();break;}
 case 'refresh-add-word':showModal(refreshEditor(data(),{selected:[id],merge:true},h));break;
 case 'refresh-legacy':showModal(refreshEditor(data(),{selected:forgottenWords(data()).map(w=>w.id),merge:true,name:'Bisherige Auffrisch-Wörter'},h));break;
 case 'refresh-check':await start('inactive-check',[id]);break;
 case 'refresh-delete':{if(!confirm('Auffrisch-Sammlung löschen? Die Originalwörter und Lernstände bleiben erhalten.'))break;await store.commit([['settings',id,null]]);closeModal();screen='collections';collectionTab='refresh';collectionFilter='all';sync.schedule();render();break;}
 case 'activity-all':await setActivity(sortedCollections(data()).map(c=>c.id),button.dataset.active==='true');break;
 case 'inactive-practice':await start('inactive-practice',[]);break;
 case 'account-logout':signOut();break;
 case 'check-update':await updates.check();break;
 case 'apply-update':await updates.apply();break;
 case 'nav':screen=button.dataset.screen;if(screen==='collections'){collectionFilter='all';search='';}closeModal();render();break;
 case 'start':await start();break;
 case 'training-options':trainingOptions();break;
 case 'start-all':await start('all');break;
 case 'start-learning':await start('learning');break;
 case 'start-refresh':await start('refresh');break;
 case 'pause':{const {session}=current();if(session.mode!=='inactive-check'&&!session.feedback)session.answers=readAnswers();await store.update(doc=>{doc.session=session;return doc;});await store.recordActivity?.('paused');sync.schedule();screen='learn';render();break;}
 case 'finish':await store.update(doc=>{doc.session=null;return doc;});screen='learn';render();break;
 case 'next':await next();break;
 case 'dont-know':await checkAnswer(true);break;
 case 'add-answer':{const el=document.querySelector('#answers');el.insertAdjacentHTML('beforeend',answerInput('',el.children.length,false));el.lastElementChild.querySelector('input').focus();break;}
 case 'remove-answer':button.closest('.answer-row').remove();break;
 case 'accept-typo':{const {word}=current();showModal(`<h2 id="modal-title">Welche Bedeutung meintest du?</h2><p class="muted">Passende Bedeutung auswählen.</p>${word.meanings.map((g,i)=>`<button class="button secondary wide meaning-choice" data-action="confirm-typo" data-index="${h(button.dataset.index)}" data-group="${i}">${h(g[0])}</button>`).join('')}`);break;}
 case 'confirm-typo':{const {session}=current();session.overrides[button.dataset.index]=Number(button.dataset.group);closeModal();await reevaluate();break;}
 case 'filter':collectionFilter=id;render();break;
 case 'edit-word':case 'new-word':case 'edit-word-fields':if(screen==='test'&&!store.doc.session.feedback){const answers=readAnswers();await store.update(doc=>{doc.session.answers=answers;return doc;});}if(action==='edit-word'&&screen==='test'){showModal(`<h2 id="modal-title">${h(data().words[id]?.latin)}</h2><div class="word-tools"><button class="button primary wide" data-action="confusion-manage" data-id="${h(id)}">${icon('repeat')} Verwechslungsgefahr einstellen</button><button class="button secondary wide" data-action="refresh-add-word" data-id="${h(id)}">Zur Auffrisch-Sammlung hinzufügen</button><button class="button secondary wide" data-action="edit-word-fields" data-id="${h(id)}">${icon('edit')} Vokabeleintrag bearbeiten</button></div>`);}else wordModal(id);break;
 case 'add-meaning':document.querySelector('#meaning-inputs').insertAdjacentHTML('beforeend',meaningInput());document.querySelector('#meaning-inputs').lastElementChild.querySelector('input').focus();break;
 case 'remove-meaning':if(document.querySelectorAll('.meaning-input').length>1)button.closest('.meaning-input').remove();break;
 case 'delete-word':{const w=data().words[id];showModal(`<h2 id="modal-title">Vokabel löschen?</h2><p>„${h(w.latin)}“ wird aus deiner Sammlung entfernt.</p><button class="button danger wide" data-action="confirm-delete-word" data-id="${h(id)}">Vokabel löschen</button>`);break;}
 case 'confirm-delete-word':await store.commit([['words',id,null]]);closeModal();sync.schedule();render();notify('Vokabel gelöscht.');break;
 case 'new-collection':case 'rename-collection':showModal(`<h2 id="modal-title">${id?'Sammlung umbenennen':'Neue Sammlung'}</h2><form id="collection-form" data-id="${h(id||uid())}"><label>Name<input name="name" required maxlength="100" value="${h((data().collections[id]||data().settings[id])?.name||'')}" placeholder="Lektion 11–18"></label><button type="submit" class="button primary wide">Speichern</button></form>`);break;
 case 'delete-collection':showModal(`<h2 id="modal-title">Sammlung löschen?</h2><p>„${h(data().collections[id].name)}“ und ihre Vokabeln werden auf allen verbundenen Geräten entfernt, sobald sie synchronisiert sind.</p><button class="button danger wide" data-action="confirm-delete-collection" data-id="${h(id)}">Sammlung löschen</button>`);break;
 case 'confirm-delete-collection':{const words=Object.values(data().words).filter(w=>w.collectionId===id);await store.commit([['collections',id,null],...words.map(w=>['words',w.id,null])]);collectionFilter='all';screen='collections';closeModal();sync.schedule();render();break;}
 case 'import':importModal();break;
 case 'confirm-import':{if(!importCandidate)break;const x=importCandidate;await store.commit(importChanges(x));importCandidate=null;closeModal();screen='collections';collectionTab=x.deck?'refresh':'lessons';collectionFilter=x.deck?.id||x.collection.id;sync.schedule();render();notify(`${x.deck?x.deck.members.length:x.words.length} Vokabeln importiert.`);break;}
 case 'theme':await changePrefs({theme:id});break;
 case 'sync-info':screen='settings';render();break;
 case 'sync-now':sync.lastFullSync=0;await cloudWait.run('Wir gleichen alles ab.');render();break;
 case 'remote':await cloudWait.run('Wir gleichen alles ab.');render();break;
 case 'close-modal':closeModal();break;
 case 'download-example':{const example={format:'latinio-collection',schema:1,name:'Meine neue Sammlung',words:[{latin:'exemplum',meanings:[['Beispiel']],forms:['exempla','exemplorum','exemplis']}]};const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(example,null,2)],{type:'application/json'}));a.download='latinio-import-beispiel.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);break;}
 }}catch(error){notify(error.message);}finally{working=false;void sharing?.afterAction();autoUpdate();}}
document.addEventListener('click',actions);
document.addEventListener('toggle',event=>{const el=event.target;if(el.dataset?.panel&&el.isConnected){if(el.open)openPanels.add(el.dataset.panel);else openPanels.delete(el.dataset.panel);}},true);
document.addEventListener('input',event=>{if(event.target.id==='refresh-word-search'){const q=normalize(event.target.value);document.querySelectorAll('[data-refresh-word-row]').forEach(row=>row.hidden=!normalize(row.textContent).includes(q));}if(event.target.id==='classroom-search'){classroomQuery=event.target.value;document.querySelector('#classroom-results').innerHTML=classroomResults(data(),classroomQuery,h);}if(event.target.id==='search'){search=event.target.value;const results=document.querySelector('#collection-search-results');if(results)results.innerHTML=search.trim()?wordRows('all',search):'';else document.querySelector('#word-list').innerHTML=wordRows();}});
document.addEventListener('change',async event=>{const el=event.target;try{
 if(el.id==='collection-select'){collectionFilter=el.value;render();}
 
 if(el.dataset.refreshActive){const deck=data().settings[el.dataset.refreshActive];if(deck){await store.commit([['settings',deck.id,{...deck,active:el.checked}]]);sync.schedule();render();}}
 if(el.name==='target'&&el.closest('#refresh-form')){const label=document.querySelector('#refresh-name-label');label.hidden=!!el.value;label.querySelector('input').required=!el.value;}
 if(el.name==='word'&&el.closest('#refresh-form'))document.querySelector('#refresh-selected-count').textContent=document.querySelectorAll('#refresh-form [name=word]:checked').length+' Wörter ausgewählt';
 if(el.dataset.activity){await setActivity([el.dataset.activity],el.checked);}
 if(el.dataset.select){selected=[...document.querySelectorAll('[data-select]:checked')].map(e=>e.dataset.select);}
 if(el.id==='daily')await changePrefs({daily:Number(el.value)});
 if(el.id==='typos')await changePrefs({typos:el.checked});
 if(el.id==='import-file'&&el.files[0]){if(el.files[0].size>3000000)throw Error('Bitte eine Datei unter 3 MB auswählen.');importCandidate=parseCollectionFile(JSON.parse(await el.files[0].text()),data());const x=importCandidate;document.querySelector('#import-preview').innerHTML=`<h3>${h(x.deck?.name||x.collection.name)}</h3><p>${x.deck?x.deck.members.length:x.words.length} Vokabeln${x.skipped?` · ${x.skipped} doppelte Einträge übersprungen`:''}${x.deck?` · Auffrisch-Sammlung · ${x.linked} vorhandene Wörter verknüpft`:''}</p><ul>${(x.previewWords||x.words).slice(0,4).map(w=>`<li><strong>${h(w.latin)}</strong> – ${h(w.meanings.map(g=>g[0]).join(', '))}</li>`).join('')}</ul><button class="button primary wide" data-action="confirm-import">Sammlung importieren</button>`;}
 }catch(error){importCandidate=null;notify(error.message);}});
document.addEventListener('submit',async event=>{event.preventDefault();if(!ready||working||cloudWait?.blocked)return;working=true;const form=event.target;const fd=new FormData(form);try{
 if(await sharing.submit(form))return;
 if(form.id==='check-picker-form'){const ids=fd.getAll('lesson');if(!ids.length)throw Error('Wähle mindestens eine Lektion aus.');refreshFlow={target:form.dataset.target,sourceIds:ids};showModal(refreshMethod());}
 if(form.id==='refresh-create-form'){const id='refresh_'+uid();const deck=saveDeck(data(),null,id,String(fd.get('name')||''),[]);await store.commit([['settings',id,deck]]);collectionTab='refresh';collectionFilter=id;search='';screen='collection-detail';closeModal();sync.schedule();render();refreshFlow={target:id,sourceIds:[]};showModal(checkPicker(data(),h,id));}
 if(form.id==='refresh-form'){
  const target=form.dataset.id||fd.get('target')||'refresh_'+uid(),existing=data().settings[target];
  const chosen=fd.getAll('word');
  const ids=form.dataset.merge==='true'?[...(existing?.members||[]).map(m=>m.wordId),...chosen]:chosen;
  let deck=saveDeck(data(),existing,target,fd.get('target')?existing.name:String(fd.get('name')||''),ids);
  // Explicitly adding a previously completed word starts a new practice cycle.
  if(form.dataset.merge==='true'){const pending=new Set(pendingMembers(data(),existing).map(m=>m.wordId));deck.members=deck.members.map(m=>chosen.includes(m.wordId)&&!pending.has(m.wordId)?{...m,addedAt:Date.now()}:m);}
  await store.commit([['settings',target,deck]]);sync.schedule();closeModal();collectionFilter=target;collectionTab='refresh';search='';screen='collection-detail';render();notify('Gespeichert.');
 }
 if(form.id==='answer-form')await checkAnswer();
 if(form.id==='word-form'){
  const word={...data().words[form.dataset.id],id:form.dataset.id,forms:String(fd.get('forms')||'').split(',').map(f=>f.trim()).filter(Boolean),collectionId:fd.get('collectionId'),latin:fd.get('latin').trim(),meanings:fd.getAll('meaning').map(v=>v.split('/').map(x=>x.trim()).filter(Boolean)).filter(g=>g.length)};
  if(word.forms.length>300||word.forms.some(f=>f.length>100))throw Error('Höchstens 300 Suchformen mit je 100 Zeichen.');
  if(!word.latin||!word.meanings.length)throw Error('Latein und mindestens eine Bedeutung fehlen.');
  await store.commit([['words',word.id,word]]);closeModal();if(screen==='test'&&current().word?.id===word.id&&current().session.feedback){store.doc.session.overrides={};await reevaluate();}else render();sync.schedule();notify('Vokabel gespeichert.');
 }
 if(form.id==='collection-form'){const name=fd.get('name').trim();if(!name)throw Error('Bitte einen Namen eingeben.');const existing=data().settings[form.dataset.id];await store.commit([existing?.kind==='refreshDeck'?['settings',existing.id,{...existing,name}]:['collections',form.dataset.id,{id:form.dataset.id,name}]]);collectionFilter=form.dataset.id;search='';screen='collection-detail';closeModal();sync.schedule();render();}
 if(form.id==='remote-form'){
  const choices={};form.querySelectorAll('[data-conflict]').forEach(el=>choices[el.dataset.conflict]=el.value);form.querySelector('button').disabled=true;await sync.accept(choices);closeModal();render();notify('Cloud-Version geladen.');
 }
 }catch(error){notify(error.message);form.querySelectorAll('button').forEach(b=>b.disabled=false);}finally{working=false;void sharing?.afterAction();autoUpdate();}});
async function loadCloud(){sync.lastFullSync=0;if(screen==='test'&&store.doc.session&&!store.doc.session.feedback){const answers=readAnswers();await store.update(doc=>{if(doc.session&&!doc.session.feedback)doc.session.answers=answers;return doc;});}await cloudWait.run('Wir bereiten alles vor.');if(!modalRoot.children.length)render();}
async function boot(){try{
 ({store,profile}=await openAccount(app));await store.seed();sync=new Sync(store);
 sharing=sharingUI({store,sync,profile,h,showModal,closeModal,notify,render,openCollection:id=>{collectionFilter=id;search='';screen='collection-detail';closeModal();render();}});
 cloudWait=cloudGate({sync,store,name:isAdmin()?'Tiago':profile.name});
 confusions=confusionUI({store,sync,h,showModal,closeModal,notify,go:target=>{if(target==='result')void showResult();else{screen=target;render();}},render});
 if(store.doc.matchRound)screen='match';
 store.addEventListener('change',updateStatus);
 store.addEventListener('external',()=>{if(screen==='test'||screen==='match'){screen='learn';notify('Ein anderer Tab hat den Stand geändert. Du kannst die gespeicherte Runde fortsetzen.');}render();});
 sync.addEventListener('change',updateStatus);
 sync.addEventListener('remote',()=>{if(!cloudWait.blocked)void loadCloud();});
 matchMedia('(prefers-color-scheme: dark)').addEventListener('change',theme);
 render();await cloudWait.run('Wir bereiten alles vor.');ready=true;render();await store.recordActivity('opened');sync.schedule();
 async function resume(){if(!ready||document.hidden)return;await store.recordActivity('opened');await loadCloud();void updates.check();}
 document.addEventListener('visibilitychange',()=>{if(document.hidden){if(screen==='test'&&store.doc.session?.mode!=='inactive-check'&&!store.doc.session?.feedback){const answers=readAnswers();void store.update(doc=>{if(doc.session)doc.session.answers=answers;return doc;});}}else void resume();});
 window.addEventListener('pageshow',event=>{if(event.persisted)void resume();});
 setInterval(()=>{if(!document.hidden){void backgroundSync();void updates.check();autoUpdate();}},60000);
 window.addEventListener('online',()=>{void updates.check();void resume();});
 if('serviceWorker'in navigator&&location.protocol!=='file:'){try{const registration=await navigator.serviceWorker.register('./sw.js',{updateViaCache:'none'});updates.watch(registration);void updates.check();}catch{notify('Offline-Bereitstellung noch nicht möglich. Online kannst du weiterlernen.');}}
 }catch(error){app.innerHTML=`<main class="boot"><h1>Die App konnte nicht starten.</h1><p>Öffne Latinio über seine Website-Adresse in einem normalen Safari-Tab.</p><p class="muted">${h(error.message)}</p></main>`;}}
boot();
