import {predicateDecks,predicateCloudItems,predicateProgress} from './predicates.js';

export function predicateList(data,h,icon){
 return `<section class="card collection-learning"><div class="collection-list-toolbar"><button class="text-button" data-action="predicate-activity-all" data-active="true">Alle ein</button><button class="text-button" data-action="predicate-activity-all" data-active="false">Alle aus</button><button class="text-button collection-new" data-action="predicate-new">Neue Sammlung</button></div><div class="bounded-list">${predicateDecks(data).map(deck=>`<div class="setting-row"><label class="collection-activity"><span><strong>${h(deck.name)}</strong><small>${deck.active!==false?'Aktiv':'Inaktiv'} · ${predicateCloudItems(data).filter(item=>item.deckId===deck.id).length} Formen</small></span><input type="checkbox" class="switch" data-predicate-active="${h(deck.id)}" ${deck.active!==false?'checked':''} aria-label="${h(deck.name)} aktiv lernen"></label><button class="icon-button" data-action="predicate-open" data-id="${h(deck.id)}" aria-label="${h(deck.name)} bearbeiten">${icon('edit')}</button></div>`).join('')||'<p class="muted">Noch keine Perfekt-Sammlung. Lege eine Sammlung an oder importiere sie in den Einstellungen.</p>'}</div></section>`;
}
export function predicateDetail(data,id,h,icon){
 const deck=predicateDecks(data).find(row=>row.id===id);
 if(!deck)return '<p>Sammlung nicht mehr vorhanden.</p><button class="text-button" data-action="nav" data-screen="collections">← Sammlungen</button>';
 return `<button class="text-button" data-action="nav" data-screen="collections">← Sammlungen</button><div class="page-heading collection-detail-heading"><div class="collection-title"><h1>${h(deck.name)}</h1><button class="icon-button" data-action="predicate-rename" data-id="${h(id)}" aria-label="Sammlung umbenennen">${icon('edit')}</button></div><button class="button primary" data-action="predicate-add" data-id="${h(id)}">${icon('plus')} Form hinzufügen</button></div><button class="text-button danger-text" data-action="predicate-delete" data-id="${h(id)}">Sammlung löschen</button><section class="word-list">${predicateCloudItems(data).filter(item=>item.deckId===id).map(item=>{const progress=predicateProgress(data,item);return `<article class="word-row"><div><strong>${h(item.grundform)}</strong></div><p>${item.praedikate.map(h).join(' / ')}</p><span class="word-level ${progress.known?'known':progress.seen?'learning':'new'}">${progress.known?'Sicher':progress.seen?'Im Training':'Neu'}</span><button class="icon-button" data-action="predicate-edit" data-id="${h(item.id)}" aria-label="${h(item.grundform)} bearbeiten">${icon('edit')}</button></article>`;}).join('')||'<p class="muted empty-state">Diese Sammlung ist noch leer.</p>'}</section>`;
}
export function predicateDeckForm(deck,h){return `<h2 id="modal-title">${deck?'Sammlung umbenennen':'Neue Perfekt-Sammlung'}</h2><form id="predicate-deck-form" data-id="${h(deck?.id||'')}"><label>Name<input name="name" required maxlength="100" value="${h(deck?.name||'')}" placeholder="Perfektformen Lektion 1"></label><button class="button primary wide" type="submit">Speichern</button></form>`;}
export function predicateItemForm(deck,item,h){return `<h2 id="modal-title">${item?'Form bearbeiten':'Neue Perfektform'}</h2><form id="predicate-item-form" data-deck="${h(deck.id)}" data-id="${h(item?.id||'')}"><label>Grundform<input name="grundform" required maxlength="180" value="${h(item?.grundform||'')}" autocapitalize="none" spellcheck="false"></label><label>Perfektform / Prädikat<input name="praedikat" required maxlength="2000" value="${h(item?.praedikate.join(' | ')||'')}" autocapitalize="none" spellcheck="false"></label><p class="small muted">Mehrere gültige Antworten mit | trennen.</p><div class="button-row"><button class="button primary" type="submit">Speichern</button>${item?`<button class="button danger" type="button" data-action="predicate-delete-item" data-id="${h(item.id)}">Löschen</button>`:''}</div></form>`;}
