import {sortedCollections,refreshDecks,deckMembers,pendingMembers} from './refresh-decks.js';
export function refreshCreate(){return '<h2 id="modal-title">Neue Auffrisch-Sammlung</h2><form id="refresh-create-form"><label>Name<input name="name" required maxlength="100" placeholder="Auffrischen Lektion 1–10" autofocus></label><button class="button primary wide" type="submit">Anlegen</button></form>';}
export function collectionToolbar(refresh=false){return `<div class="collection-list-toolbar"><button class="text-button" data-action="${refresh?'refresh-activity-all':'activity-all'}" data-active="true">Alle ein</button><button class="text-button" data-action="${refresh?'refresh-activity-all':'activity-all'}" data-active="false">Alle aus</button><button class="text-button collection-new" data-action="${refresh?'refresh-new':'new-collection'}">Neue Sammlung</button></div>`;}
export function collectionRow(c,active,refresh,h,icon){return `<div class="setting-row"><label class="collection-activity"><span><strong>${h(c.name)}</strong><small>${active?'Aktiv':'Inaktiv'}</small></span><input type="checkbox" class="switch" ${refresh?'data-refresh-active':'data-activity'}="${h(c.id)}" ${active?'checked':''} aria-label="${h(c.name)} aktiv lernen"></label><button class="icon-button" data-action="${refresh?'refresh-tools':'collection-open'}" data-id="${h(c.id)}" aria-label="${h(c.name)} bearbeiten">${icon('edit')}</button></div>`;}
export function refreshList(data,h,icon=()=> '✎'){return `<section class="card collection-learning">${collectionToolbar(true)}<div class="bounded-list">${refreshDecks(data).map(d=>collectionRow(d,d.active!==false,true,h,icon)).join('')||'<p class="muted">Noch keine Auffrisch-Sammlung.</p>'}</div></section>`;}
export function refreshTools(data,id,h){const d=data.settings[id];if(!d||d.kind!=='refreshDeck')return '<h2 id="modal-title">Sammlung nicht mehr vorhanden.</h2>';const total=deckMembers(data,d).length,pending=pendingMembers(data,d).length;return `<h2 id="modal-title">${h(d.name)}</h2><p class="small muted">${pending} offen · ${total-pending} erledigt</p><div class="refresh-actions"><button class="button secondary" data-action="refresh-edit" data-id="${h(id)}">Vokabeln & Namen bearbeiten</button><button class="button secondary" data-action="check-picker" data-id="${h(id)}">Test starten</button><button class="button primary" data-action="refresh-practice" data-id="${h(id)}" ${!pending||d.active===false?'disabled':''}>Gesammelte Wörter üben</button><button class="button secondary" data-action="refresh-restart" data-id="${h(id)}">Alle erneut üben</button><button class="text-button danger-text" data-action="refresh-delete" data-id="${h(id)}">Sammlung löschen</button></div>`;}
export function checkPicker(data,h,target=''){return `<h2 id="modal-title">Test starten</h2><p class="muted" data-compact-hide>Lektionen auswählen. Unsichere Wörter anschließend übernehmen.</p><form id="check-picker-form" data-target="${h(target)}"><div class="bounded-list">${sortedCollections(data).map(c=>`<label class="collection-check"><input type="checkbox" name="lesson" value="${h(c.id)}"><span>${h(c.name)}</span></label>`).join('')}</div><button class="button primary wide" type="submit">Test starten</button></form>`;}
export function refreshEditor(data,{id='',selected=[],name='',merge=false},h){
 const deck=data.settings[id],chosen=new Set(deck&&!merge?deckMembers(data,deck).map(m=>m.wordId):selected);
 const words=sortedCollections(data).flatMap(c=>Object.values(data.words).filter(w=>w.collectionId===c.id));
 return `<h2 id="modal-title">${id?'Auffrisch-Sammlung bearbeiten':'Wörter zum Auffrischen'}</h2><form id="refresh-form" data-id="${h(id)}" data-merge="${merge}">${merge&&!id?`<label>Speichern in<select name="target"><option value="">Neue Auffrisch-Sammlung</option>${refreshDecks(data).map(d=>`<option value="${h(d.id)}">${h(d.name)}</option>`).join('')}</select></label>`:''}<label id="refresh-name-label">Name<input name="name" maxlength="100" value="${h(deck?.name||name||'Meine Auffrisch-Sammlung')}" required></label><p class="small muted" data-compact-hide>Wörter auswählen oder abwählen.</p><input type="search" id="refresh-word-search" placeholder="Wörter oder Lektion filtern" aria-label="Wörter filtern"><div class="bounded-list refresh-word-picker">${words.map(w=>`<label class="collection-check" data-refresh-word-row><input type="checkbox" name="word" value="${h(w.id)}" ${chosen.has(w.id)?'checked':''}><span><strong>${h(w.latin)}</strong><small>${h(w.meanings.map(g=>g.join(' / ')).join(', '))} · ${h(data.collections[w.collectionId].name)}</small></span></label>`).join('')}</div><p class="small" id="refresh-selected-count">${chosen.size} Wörter ausgewählt</p><button class="button primary wide" type="submit">Auswahl speichern</button></form>`;
}
