import {sortedCollections,refreshDecks,deckMembers,pendingMembers} from './refresh-decks.js';
export function refreshCreate(english=false){return `<h2 id="modal-title">Neue Auffrisch-Sammlung</h2><form id="refresh-create-form"><label>Name<input name="name" required maxlength="100" placeholder="Auffrischen Lektion 1–10" autofocus></label>${english?'<label>Abfragerichtung<select name="direction"><option value="both">Beide Richtungen · jedes Wort zweimal</option><option value="en-de">Nur Englisch → Deutsch</option><option value="de-en">Nur Deutsch → Englisch</option></select></label>':''}<button class="button primary wide" type="submit">Anlegen</button></form>`;}
export function collectionToolbar(refresh=false){return `<div class="collection-list-toolbar"><button class="text-button" data-action="${refresh?'refresh-activity-all':'activity-all'}" data-active="true">Alle ein</button><button class="text-button" data-action="${refresh?'refresh-activity-all':'activity-all'}" data-active="false">Alle aus</button><button class="text-button collection-new" data-action="${refresh?'refresh-new':'new-collection'}">Neue Sammlung</button></div>`;}
export function collectionRow(c,active,refresh,h,icon){return `<div class="setting-row"><label class="collection-activity"><span><strong>${h(c.name)}</strong><small>${active?'Aktiv':'Inaktiv'}</small></span><input type="checkbox" class="switch" ${refresh?'data-refresh-active':'data-activity'}="${h(c.id)}" ${active?'checked':''} aria-label="${h(c.name)} aktiv lernen"></label><button class="icon-button" data-action="${refresh?'refresh-tools':'collection-open'}" data-id="${h(c.id)}" aria-label="${h(c.name)} bearbeiten">${icon('edit')}</button></div>`;}
export function refreshList(data,h,icon=()=> '✎'){return `<section class="card collection-learning">${collectionToolbar(true)}<div class="bounded-list">${refreshDecks(data).map(d=>collectionRow(d,d.active!==false,true,h,icon)).join('')||'<p class="muted">Noch keine Auffrisch-Sammlung.</p>'}</div></section>`;}
export function checkPicker(data,h,target='',selected=[]){return `<h2 id="modal-title">Lektionen auswählen</h2><form id="check-picker-form" data-target="${h(target)}"><div class="bounded-list">${sortedCollections(data).map(c=>`<label class="collection-check"><input type="checkbox" name="lesson" value="${h(c.id)}" ${selected.includes(c.id)?'checked':''}><span>${h(c.name)}</span></label>`).join('')}</div><button class="button primary wide" type="submit">Weiter</button></form>`;}
export function refreshMethod(english=false,direction='both'){return `<h2 id="modal-title">Vokabeln hinzufügen</h2><div class="refresh-actions">${english?`<label>Test-Richtung<select id="refresh-direction"><option value="both" ${direction==='both'?'selected':''}>Beide Richtungen · jedes Wort zweimal</option><option value="en-de" ${direction==='en-de'?'selected':''}>Nur Englisch → Deutsch</option><option value="de-en" ${direction==='de-en'?'selected':''}>Nur Deutsch → Englisch</option></select></label>`:''}<button class="button secondary" data-action="refresh-select-manual">Zu wiederholende Vokabeln auswählen</button><div class="refresh-test-choice"><button class="button primary" data-action="refresh-select-test">Testmodus</button><details class="test-explanation"><summary aria-label="Testmodus erklären">?</summary><p>Drehe jede Karte um und entscheide selbst: rechts wischen heißt gewusst, links heißt nicht gewusst. Nicht gewusste Wörter werden am Ende automatisch in deine Auffrisch-Sammlung aufgenommen.</p></details></div><button class="text-button" data-action="refresh-select-back">← Lektionen</button></div>`;}
export function refreshReconcileEditor(result,deckId,h){
 const rows=result.unmatched.map(({word,candidates})=>{
  const suggested=new Set(candidates.map(x=>x.id));
  const options=list=>list.map(x=>`<option value="${h(x.id)}">${h(x.latin)} · ${h(x.collection)}</option>`).join('');
  return `<div class="import-resolution"><strong>${h(word.latin)}</strong><small class="muted">${h(word.meanings.map(g=>g.join(' / ')).join(', '))}</small><label>Vorhandene Vokabel suchen<input type="search" data-reconcile-search="${h(word.id)}" data-candidates="${h(JSON.stringify(candidates))}" placeholder="Latein, Bedeutung oder Lektion"></label><label>Zuordnen<select id="reconcile-select-${h(word.id)}" name="legacy-${h(word.id)}"><option value="">Nicht zuordnen</option>${candidates.length?`<optgroup label="Mögliche Treffer">${options(candidates)}</optgroup>`:''}</select></label></div>`;
 }).join('');
 return `<h2 id="modal-title">Auffrisch-Vokabeln überprüfen</h2><p class="muted">${result.automatic?`${result.automatic} eindeutige Vokabeln werden automatisch mit den Originalen verknüpft. `:''}Ordne unklare Treffer bei Bedarf manuell zu. Nicht zugeordnete Einträge bleiben vorerst erhalten.</p><form id="refresh-reconcile-form" data-id="${h(deckId)}">${rows}<button class="button primary wide" type="submit">${rows?'Zuordnungen speichern':'Schließen'}</button></form>`;
}
export function refreshEditor(data,{id='',selected=[],name='',merge=false,sourceIds=null},h){
 const deck=data.settings[id],chosen=new Set(deck&&!merge?deckMembers(data,deck).map(m=>m.wordId):selected);
 const words=sortedCollections(data).filter(c=>!sourceIds||sourceIds.includes(c.id)).flatMap(c=>Object.values(data.words).filter(w=>w.collectionId===c.id));
 return `<h2 id="modal-title">${id?'Auffrisch-Sammlung bearbeiten':'Wörter zum Auffrischen'}</h2><form id="refresh-form" data-id="${h(id)}" data-merge="${merge}">${merge&&!id?`<label>Speichern in<select name="target"><option value="">Neue Auffrisch-Sammlung</option>${refreshDecks(data).map(d=>`<option value="${h(d.id)}">${h(d.name)}</option>`).join('')}</select></label>`:''}<label id="refresh-name-label" ${id?'hidden':''}>Name<input name="name" maxlength="100" value="${h(deck?.name||name||'Meine Auffrisch-Sammlung')}" required></label><p class="small muted" data-compact-hide>Wörter auswählen oder abwählen.</p><input type="search" id="refresh-word-search" placeholder="Wörter oder Lektion filtern" aria-label="Wörter filtern"><div class="bounded-list refresh-word-picker">${words.map(w=>`<label class="collection-check" data-refresh-word-row><input type="checkbox" name="word" value="${h(w.id)}" ${chosen.has(w.id)?'checked':''}><span><strong>${h(w.latin)}</strong><small>${h(w.meanings.map(g=>g.join(' / ')).join(', '))} · ${h(data.collections[w.collectionId].name)}</small></span></label>`).join('')}</div><p class="small" id="refresh-selected-count">${chosen.size} Wörter ausgewählt</p><button class="button primary wide" type="submit">Auswahl speichern</button></form>`;
}
