// Animation-only sandbox. No store, cloud, progress, or streak dependencies.
const variants={ember:{title:'Funke',description:'Für normale Tage: eine lebendige Flamme und ein sanfter Tageswechsel.'},impact:{title:'Einschlag',description:'Die Zahl kommt aus der Tiefe, landet und sendet einen leuchtenden Ring aus.'},orbit:{title:'Feuerkreis',description:'Lichtpunkte kreisen um die Flamme und feiern den neuen Tag.'}};
const days=[1,2,3,7,30,100];
export function streakLab(day=1){
 return `<h2 id="modal-title">Admin Tests</h2><p class="muted">Streak-Animationen ausprobieren. Dies sind reine Vorschauen; es wird nichts gespeichert.</p><label class="streak-day-picker">Vorschautag<select id="streak-demo-day">${days.map(n=>`<option value="${n}" ${n===day?'selected':''}>Tag ${n}${[1,30,100].includes(n)?' · Meilenstein':''}</option>`).join('')}</select></label><div class="streak-demo-options">${Object.entries(variants).map(([id,v])=>`<article><h3>${v.title}</h3><p class="small muted">${v.description}</p><button class="button primary wide" data-action="streak-demo" data-id="${id}">Animation ansehen</button></article>`).join('')}</div><p class="small muted">Tipp: Vergleiche Tag 1, 30 und 100. Farben und Abschluss passen sich dem Meilenstein an. Mit „Wiederholen“ kannst du dieselbe Variante erneut ansehen.</p>`;
}
function flame(){return `<svg class="streak-flame" viewBox="0 0 120 150" aria-hidden="true"><defs><linearGradient id="streak-fire" x1="0" y1="1" x2=".65" y2="0"><stop stop-color="var(--fire-deep)"/><stop offset=".65" stop-color="var(--fire)"/><stop offset="1" stop-color="var(--fire-light)"/></linearGradient></defs><path fill="url(#streak-fire)" d="M61 3c12 26 1 36 16 54 4-11 9-16 14-20 4 23 24 39 24 64 0 29-23 46-54 46S6 129 6 100c0-23 13-36 25-48-1 18 4 24 9 28C33 46 53 28 61 3Z"/><path fill="var(--fire-light)" d="M61 76c6 15 0 24 12 31 2-6 5-10 8-13 7 12 10 18 10 26 0 14-13 25-30 25s-31-11-31-25c0-15 14-26 17-35 0 9 3 14 6 16-1-10 1-18 8-25Z"/></svg>`;}
export function streakDemo(day,variant='impact'){
 day=days.includes(Number(day))?Number(day):1;variant=Object.hasOwn(variants,variant)?variant:'impact';
 const special=[1,30,100].includes(day),caption=day===1?'Dein erster Funke.':day===30?'Ein ganzer Monat voller Feuer.':day===100?'100 Tage. Ein echtes Feuerwerk.':'Du bleibst dran.',particles=Array.from({length:18},(_,i)=>`<i style="--angle:${i*20}deg;--delay:${(i%6)*.07}s;--reach:${110+(i%4)*22}px"></i>`).join('');
 return `<div class="streak-stage ${special?'streak-special':''}" data-variant="${variant}" data-day="${day}"><div class="streak-wash" aria-hidden="true"></div><div class="streak-orbit" aria-hidden="true">${particles}</div><div class="streak-halo" aria-hidden="true"></div><div class="streak-scene"><div class="streak-flame-wrap">${flame()}</div><div class="streak-counter" aria-hidden="true">${day>1?`<span class="streak-old">${day-1}</span>`:''}<span class="streak-new">${day}</span></div><h2 id="modal-title" class="streak-day-label">Tag ${day}</h2><p class="streak-caption">${caption}</p></div><div class="streak-demo-controls"><span class="small">Animationsvorschau · ${variants[variant].title}</span><div><button class="streak-replay" data-action="streak-demo-replay">↻ Wiederholen</button><button class="streak-back" data-action="admin-tests">Zur Auswahl</button></div></div></div>`;
}
