// Transkription der beiden bereitgestellten Seiten. Kommagetrennte Bedeutungen
// bleiben getrennte Lernziele; Klammerteile sind bei der Eingabe optional.
const rows = [
['gerere','ausführen','führen','tragen'],
['remanere','(zurück)bleiben'],
['agere','handeln','treiben','verhandeln'],
['vox, vocis','Äußerung','Laut','Stimme'],
['mons, montis','Berg'],
['ducere','führen','ziehen'],
['propinquus','Verwandter'],
['soror, sororis','Schwester'],
['orare','bitten','beten'],
['convenire','besuchen','zusammenkommen'],
['praebere','hinhalten','geben'],
['munus, muneris','Aufgabe','Geschenk'],
['sicut','(so) wie'],
['iter, itineris','Reise','Weg','Marsch'],
['cupere','verlangen','wünschen','wollen'],
['scire','kennen','wissen','verstehen'],
['liber, libri','Buch'],
['comes, comitis','Gefährte','Begleiter'],
['capere','fassen','nehmen','erobern'],
['corripere','ergreifen','gewaltsam an sich reißen'],
['carmen, carminis','Lied','Gedicht'],
['legere','lesen','auswählen'],
['deinde','dann','darauf'],
['gaudere','sich freuen'],
['tandem','endlich'],
['patere','offenstehen','sich erstrecken'],
['contendere','eilen','sich anstrengen'],
['apud','bei','nahe bei'],
['dubitare','zögern'],
['undique','von allen Seiten'],
['nuntius','Bote','Nachricht'],
['repente','plötzlich'],
['quod','dass','weil'],
['dolere','schmerzen','bedauern'],
['pugnare','kämpfen'],
['arma','Waffen','Gerät'],
['debere','müssen','sollen','schulden'],
['periculum','Gefahr'],
['mittere','(los)lassen','schicken','werfen'],
['domina','Herrin'],
['iubere','befehlen','anordnen'],
['paulo','(um) ein wenig'],
['portare','tragen','bringen'],
['velle','wollen'],
['convivium','Gastmahl','Gelage'],
['consilium','Beratung','Beschluss','Plan','Rat']
];
export const collection={id:'lektion-1-10',name:'Lektion 1–10'};
export const vocabulary=rows.map(([latin,...meanings],i)=>({id:'l1-10-'+String(i+1).padStart(2,'0'),collectionId:collection.id,latin,meanings:meanings.map(m=>[m])}));
export const starterImport={format:'latinio-collection',schema:1,id:collection.id,name:collection.name,words:vocabulary.map(({latin,meanings})=>({latin,meanings}))};
