import test from 'node:test';import assert from 'node:assert/strict';import vm from 'node:vm';import {readFileSync} from 'node:fs';import {createHash} from 'node:crypto';
function server(){const rows=[['Version','ID','At','Device','JSON']],properties={WORDLO_SHEET_ID:'test',WORDLO_TOKEN_HASH:createHash('sha256').update('t'.repeat(40)).digest('hex')};
 const sheet={getLastRow:()=>rows.length,getRange:(start,col,count=1,width=1)=>({getValues:()=>rows.slice(start-1,start-1+count).map(r=>r.slice(col-1,col-1+width)),setValues:values=>values.forEach((row,i)=>{rows[start-1+i]=row;})})};
 const context=vm.createContext({PropertiesService:{getScriptProperties:()=>({getProperty:k=>properties[k]})},Utilities:{DigestAlgorithm:{SHA_256:'sha256'},Charset:{UTF_8:'utf8'},computeDigest:(_,value)=>Array.from(createHash('sha256').update(value).digest())},SpreadsheetApp:{openById:()=>({getSheetByName:()=>sheet}),flush:()=>{}},LockService:{getScriptLock:()=>({tryLock:()=>true,releaseLock:()=>{}})}});
 vm.runInContext(readFileSync(new URL('../google/Code.gs',import.meta.url),'utf8'),context);
 return {call:r=>JSON.parse(JSON.stringify(context.wordloApi({app:'wordlo',token:'t'.repeat(40),...r}))),rows};}
const op={id:'op-1',device:'device-a',seq:1,at:1,entity:'collections',key:'unit-1',value:{id:'unit-1',name:'Unit 1'}};
test('Wrong key and Latinio requests cannot access Wordlo',()=>{const s=server();assert.throws(()=>s.call({action:'check',token:'x'.repeat(40)}));assert.throws(()=>s.call({action:'check',app:'latinio'}));});
test('Roundtrip push and pull, monotonically versioned',()=>{const s=server();assert.equal(s.call({action:'check'}).version,0);const push=s.call({action:'push',base:0,ops:[op]});assert.equal(push.version,1);assert.equal(s.call({action:'pull',since:0}).data.collections['unit-1'].name,'Unit 1');});
test('Stale device push writes nothing',()=>{const s=server();s.call({action:'push',base:0,ops:[op]});assert.equal(s.call({action:'push',base:0,ops:[{...op,id:'op-2'}]}).conflict,true);assert.equal(s.rows.length,2);});
test('Retrying acknowledged operation does not duplicate it',()=>{const s=server();s.call({action:'push',base:0,ops:[op]});const result=s.call({action:'push',base:1,ops:[op]});assert.equal(result.version,1);assert.deepEqual(result.accepted,['op-1']);});
test('Entire invalid batch is rejected before any rows are written',()=>{const s=server();assert.throws(()=>s.call({action:'push',base:0,ops:[op,{...op,id:'op-2',key:'__proto__'}]}));assert.equal(s.rows.length,1);});
test('Server accepts full bilingual words and region metadata',()=>{const s=server();const w={id:'word-1',collectionId:null,english:[{id:'g-en',answers:['flat'],region:'UK'}],german:[{id:'g-de',answers:['Wohnung']}]};s.call({action:'push',base:0,ops:[{...op,entity:'words',key:w.id,value:w}]});assert.equal(s.call({action:'pull',since:0}).data.words['word-1'].english[0].region,'UK');});
test('Server refuses cloud rewinds and unknown operations',()=>{const s=server();assert.throws(()=>s.call({action:'pull',since:10}));assert.throws(()=>s.call({action:'login'}));});
